[env]

SODIUM_STATIC="1"
SODIUM_REL_DIR="/libsodium"
SODIUM_DIR="${CARGO_MAKE_WORKING_DIRECTORY}${SODIUM_REL_DIR}"
SODIUM_REL_INSTALL_DIR="/install_dir"
SODIUM_INSTALL_DIR="${SODIUM_DIR}${SODIUM_REL_INSTALL_DIR}"
SODIUM_LIB_DIR="${SODIUM_INSTALL_DIR}/lib"

DOCKER_CROSS_WORK_DIR="/work"
DOCKER_CROSS_SODIUM_INSTALL_DIR="${DOCKER_CROSS_WORK_DIR}${SODIUM_REL_INSTALL_DIR}"

DOCKER_CROSS_SCRIPT_NAME="dockcross"
DOCKER_CROSS_SCRIPT="${CARGO_MAKE_WORKING_DIRECTORY}/${DOCKER_CROSS_SCRIPT_NAME}"

CROSS_SODIUM_LIB_DIR="/project${SODIUM_REL_DIR}${SODIUM_REL_INSTALL_DIR}/lib"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.dockercross_download]
script = [
	"docker pull dockcross/${DOCKER_CROSS_IMAGE_NAME}"
]

[tasks.dockercross_create_script]
script = [
	"docker run --rm dockcross/${DOCKER_CROSS_IMAGE_NAME}> ./${DOCKER_CROSS_SCRIPT_NAME}",
	"chmod +x ./${DOCKER_CROSS_SCRIPT_NAME}"
]

[tasks.mv_native_lib]
script = ["cp target/${CROSS_TRIPLE}/release/libssb_sql_napi.* target/release"]

[tasks.configure_napi_binding]
script = [
"rm Makefile",
"rm CMakeCache.txt",
"rm -rf CMakeFiles",
"${DOCKER_CROSS_SCRIPT} cmake ."
]
dependencies = ["mv_native_lib"]

[tasks.build_napi_binding]
script = ["${DOCKER_CROSS_SCRIPT} make"]
dependencies = ["configure_napi_binding"]

[tasks.mv_napi_binding]
command = "mv"
args = ["libbinding.so", "binding.node"]
dependencies = ["build_napi_binding"]

[tasks.sodium_clone]
script = [
	"[ -d ${SODIUM_DIR} ] || git clone https://github.com/jedisct1/libsodium ${SODIUM_DIR}"
]

[tasks.sodium_fetch]
command = "git"
args = ["-C", "${SODIUM_DIR}","fetch"]
dependencies = ["sodium_clone"]

[tasks.sodium_checkout]
command = "git"
args = ["-C",  "${SODIUM_DIR}","checkout", "origin/stable"]
dependencies = ["sodium_fetch"]

[tasks.sodium_make_install]
script = [
	"cd ${SODIUM_DIR}",
	"${DOCKER_CROSS_SCRIPT} ./autogen.sh",
	"${DOCKER_CROSS_SCRIPT} ./configure --prefix=${DOCKER_CROSS_SODIUM_INSTALL_DIR} --disable-shared --enable-static --disable-pie --host=${DOCKER_CROSS_TRIPLE}",
	"${DOCKER_CROSS_SCRIPT} make",
	"${DOCKER_CROSS_SCRIPT} make install",
]
dependencies = ["dockercross_create_script", "sodium_checkout"]

[tasks.build_native]
script = [
"SODIUM_LIB_DIR=${CROSS_SODIUM_LIB_DIR}",
"cross build --release --target ${CROSS_TRIPLE}"
]
dependencies = ["sodium_make_install"]

[tasks.make]
script = [
		"${DOCKER_CROSS_SCRIPT} cmake -DCMAKE_BUILD_TYPE=Release .",
		"${DOCKER_CROSS_SCRIPT} make",
		"mv libbinding.so ../build/Release/binding.node",
]

[tasks.cross]
dependencies = [
		"build_native",
		"mv_native_lib",
    "sodium_make_install",
		"make"
]

[tasks.no-cross]
script = [
"cmake -DCMAKE_BUILD_TYPE=Release .",
"cargo build --release",
"make",
"mv libbinding.so ../build/Release/binding.node",
]

[tasks.no-cross-debug]
script = [
"cmake -DCMAKE_BUILD_TYPE=Debug .",
"cargo build --all",
"make",
"mv libbinding.so ../build/Release/binding.node",
]
